# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Twenty Sixteen"
license = "Apache 2.0"
licenselink = "https://github.com/TotallyInformation/hugo-theme-twenty-sixteen/blob/master/LICENSE"
description = ""
homepage = "https://github.com/TotallyInformation/hugo-theme-twenty-sixteen"
tags = []
features = ["menu","disqus"]
min_version = "0.38"

#sectionPagesMenu = "main"
enableRobotsTXT = true
Paginate = 10 # Number of posts to show before paginating
enableEmoji = true # Enable emojis in pages. e.g. :smile: - @see https://www.webpagefx.com/tools/emoji-cheat-sheet/

# RSS settings
#rssURI = "feed" # default index.xml
rssLimit = 10 # default unlimited
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."

# Disqus shortcode
# Disable comments for any individual post by adding "comments: false" in its frontmatter
#disqusShortname = ""

# Code Highlighting (uses Chroma but shares old config names for compatibility)
pygmentsCodefences = true
pygmentsUseClasses = true # Use `hugo gen chromastyles --style=monokai > static/css/syntax.css` and include in baseof.html
pygmentsCodefencesGuessSyntax = true
#pygmentsStyle = "monokai"

# -- Don't put individual entries below here or group entries above here -- #

# Template Author
[author]
  name = "Julian Knight"
  homepage = "https://it.knightnet.org.uk"

[permalinks]
  # Configures post URLs
  #posts = "/:year/:month/:slug"
  #pages = "/:slug"
  #kbs = "/kb/:slug"
  #categories = "/categories/:slug"
  #tags = "/tags/:slug

# Adds a fulltext output for use with a custom search tool
[outputFormats]
    [outputFormats.SearchIndex]
        mediaType = "application/json"
        baseName = "searchindex"
        isPlainText = true
        notAlternative = true
[outputs]
    home = ["HTML","RSS","SearchIndex"]

# related content
[related]
    # Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
    threshold = 80
    # To get stable "See also" sections we, by default, exclude newer related pages.
    includeNewer = true
    # Will lower case keywords in both queries and in the indexes.
    toLower = true

[[related.indices]]
    name = "keywords"
    weight = 0
[[related.indices]]
    name  = "author"
    toLower = true
    weight = 30
[[related.indices]]
    name  = "tags"
    weight = 100
[[related.indices]]
    name  = "date"
    weight = 10
    pattern = "2006"

[params]
    description = "Twenty-Sixteen Theme by Julian Knight (Totally Information)"

    # Default page editor's name (appears in meta tags and under posts)
    author = "Anonymous"

    # Google analytics code - remove if you do not have/want Google Analytics - needs JavaScript
    #googleAnalytics = ""

    # --- TwentySixteen Theme Parameters --- #

    # If false, all of blog post will appear on front page (and in pagination)
    truncate = true # not yet working

    # Set to true to output some helpful info - helps understand about Kind, Section, Type, etc.
    debug = false # Debug outputs to web page
    debugConsole = false # Debug outputs to browser console only

    # What elements to exclude from the navigation menu?
    menuExclude = ["Posts", "Pages"]

    # Sidebar: /layouts/partials/site-sidebar.html
    sidebarSide = "right" # left/right or comment out to disable sidebar
    sidebarWidth = 3      # Width as # of logical columns (n/12 ths), default = 3

    # Do we want social sharing icons showing? Default false
    # sharingicons = true

    # Twitter User - if set will show Twitter timeline in sidebar
    # twitterUser = "TotallyInformation"
    # Number of recent posts to show (defaults to 5)
    #twitterPosts = 5
    # Width & height in pixels (defaults to the width of the sidebar, expands to height of tweet list)
    # twitterWidth = 220
    # twitterHeight = 600
    # Twitter widget theme (See https://dev.twitter.com/web/embedded-timelines )
    # twitterTheme = "dark" # dark/light/transparent, default dark
    # twitterChrome = "" # default "nofooter noborders"

    # Follow icons - NB: includes showing the RSS feed icon
    followicons = false
    #followtwitter = "" # Twitter https://twitter.com/<<followtwitter>>
    #followfb = "" # Facebook https://www.facebook.com/julian.knight.0
    #followgplus = "JulianKnight-IT" # Google+ https://plus.google.com/u/0/+<<followfb>>
    #followli = "" # LinkedIn https://www.linkedin.com/in/<<followli>>/
    #followgh = "" # GitHub https://github.com/<<followgh>>
    #followse = "" # Stack Exchange https://stackexchange.com/users/<<followse>> NB: the user number not name
    # Other possibilities not yet implemented: codepen, keybase, flickr, instagram, email, pintrest

    # Flairs
    #seflair = "#######" # Stack Exchange https://stackexchange.com/users/#######/name
    #ptpflair = false # https://www.protruthpledge.org/

[params.sitemeta]
    # schema.org metadata
    [params.sitemeta.publisher]
        # Publisher is required for "@type" : "BlogPosting"
        name = "My Org"  # Organization name (maybe use owner name if no org or comment out)
        #url  = "https://www.sample.com" # Org url (optional)
        #founder = "My Name" # Name of the founder (optional)
        #sameAs  = [  ] # List of other URL's related to this org (optional)
    #[params.sitemeta.publisher.address]
        # For privacy, only includes locality and country (optional)
        #addressLocality = "Sheffield"
        #addressCountry = "GB"
    #[params.sitemeta.publisher.logo]
        # Logo is included in the Publisher section if defined here (optional) - comment out to ignore
        #url    = "/images/MyOrg-600x60-whitebg.png"
        # NOTE that Google demand org logos to be 600x60 px
        #width  = "600"
        #height = "60"
